remote_theme: daattali/beautiful-jekyll@6.0.1

# personal gibberish
title: "Aditya Somasundaram's website"
descripition: Listen to the rant of Aditya Somasundaram.
author: Aditya Somasundaram

# links to stuff
navbar-links:
  About Me: "about"
  Publications: "pubs"
  # Current Work: "rant"
  Chess: "chess"
  Résumé: "https://drive.google.com/file/d/1kS2t9ncz68hWYU4_X2Ua76Jm9Qlu0LRr/view?usp=sharing"

title-img: "https://aditsom.github.io/AdityaSomasundaram/assets/img/dp_circle.png"

# nav properties
navbar-col: "#99cbe8"
navbar-text-col: "#3e6fb6"
navbar-children-col: "#a8eff0"
page-col: "#f0f7f7"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#99cbe8"
footer-text-col: "#3e6fb6"
footer-link-col: "#404040"

# social network links
social-network-links:
  email: "aditsom7@gmail.com"
  google-scholar: citations?user=wvh68FUAAAAJ&hl=en
  linkedin: adityasomasundaram
  twitter: aditsom7

# url-pretty: 

# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "G-L0E45BRZPT"

# # Default YAML values (more information on Jekyll's site)
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       comments: true  # add comments to all blog posts
#       social-share: true # add social media sharing buttons to all blog posts
#       readtime: true # add estimated reading time on all blog posts
#   -
#     scope:
#       path: "" # all files
#     values:
#       layout: "page"
#       show-avatar: true

# #Meta data for your Posts
# metadata:
#   _posts:
#     - name: "layout"
#       field:
#         element: "hidden"
#         value: "post"
#     - name: "title"
#       field:
#         element: "text"
#         label: "Post title"
#         placeholder: "Title"
#         alterable: true
#     - name: "subtitle"
#       field:
#         element: "textarea"
#         label: "Subtitle"
#         placeholder: "A description of your post."
#         alterable: true
#     - name: "date"
#       field:
#         element: "text"
#         label: "Date"
#         help: "Enter date of post."
#         placeholder: "yyyy-mm-dd"
#         alterable: true
#     - name: "image"
#       field:
#         element: "text"
#         label: "Image"
#         help: "Add a thumbnail image to your post."
#         placeholder: "Thumbnail"
#         alterable: true
#     - name: "published"
#       field:
#         element: "checkbox"
#         label: "Publish"
#         help: "Check to publish post, uncheck to hide."

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - docs/

paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  
